filter:
    path: [src/*]
    excluded_paths: [vendor/*, tests/*]
tools:
    external_code_coverage: true
    php_mess_detector:
            enabled: true
            extensions:
                - php
            command: phpmd
            filter:
                paths: {  }
                excluded_paths:
                    - 'tests/*'
                    - 'vendor/*'
            config:
                rulesets:
                    - codesize
    php_cs_fixer:
        enabled: true
        extensions:
            - php
        command: php-cs-fixer
        config:
            level: psr2
    php_analyzer:
        enabled: true
        filter:
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'
        extensions:
            - php
    php_pdepend: true
    php_cpd:
       enabled: true
       excluded_dirs: [vendor, tests]
    external_code_coverage: true
before_commands:
    - "composer install --dev --prefer-source"
