<?php
namespace Itkg\Helper;

use Itkg\Helper\DataValidator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-10 at 11:40:33.
 */
class DataValidatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DataValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DataValidator();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    /**
     * @covers Itkg\Helper\DataValidator::isDateAAAAMMDD
     * 
     */
    public function testIsDateAAAAMMDD()
    {
        $dDate = date('Y-m-d');
        $this->assertTrue($this->object->isDateAAAAMMDD($dDate));
        
        $dDate = date('Ymd');
        $this->assertFalse($this->object->isDateAAAAMMDD($dDate));
        
        $dDate = "";
        $this->assertTrue($this->object->isDateAAAAMMDD($dDate));
        
    }
}