<?php
namespace Itkg\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-01-16 at 18:57:46.
 */
class FonctionnalExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FonctionnalException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FonctionnalException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    /**
     * @covers Itkg\Exception\FonctionnalException::getTrame
     */
    public function testgetTrame()
    {
        $this->object->setTrame("mytrame");
        $this->assertEquals($this->object->getTrame(), "mytrame");
    }
    /**
     * @covers Itkg\Exception\FonctionnalException::setTrame
     */
    public function testsetTrame()
    {
        $this->object->setTrame("mytrame");
        $this->assertEquals($this->object->getTrame(), "mytrame");
    }
    /**
     * @covers Itkg\Exception\FonctionnalException::getDatas
     */
    public function testgetDatas()
    {
        $this->object->setDatas("datas");
        $this->assertEquals($this->object->getDatas(), "datas");
    }
    /**
     * @covers Itkg\Exception\FonctionnalException::setDatas
     */
    public function testsetDatas()
    {
        $this->object->setDatas("datas");
        $this->assertEquals($this->object->getDatas(), "datas");
    }
}
