<?php
namespace Itkg\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-01-16 at 18:52:58.
 */
class NotFoundExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NotFoundException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NotFoundException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    public function testConstruct()
    {
        $this->object = new NotFoundException("test");
        $this->assertEquals($this->object->getMessage(), "test");
    }
}
