<?php
namespace Itkg\Exception;

use Itkg\Exception\UnauthorizedException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-07 at 11:00:04.
 */
class UnauthorizedExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UnauthorizedException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UnauthorizedException;
       
    }

    //Verification simplement que les constantes sont correctes : il n y a pas de méthodes à tester
    public function testConstantes ()
    {
        $testValue = '0';
        $realValue = UnauthorizedException::NON_ABONNE;
        $this->assertEquals($testValue, $realValue);
        
        $testValue = '1';
        $realValue = UnauthorizedException::NON_INSCRIT;
        $this->assertEquals($testValue, $realValue);
        
        $testValue = '2';
        $realValue = UnauthorizedException::MAUVAIS_PROFIL;
        $this->assertEquals($testValue, $realValue);
        
        
        $testValue = '1';
        $realValue = UnauthorizedException::NON_ABONNE;
        $this->assertNotEquals($testValue, $realValue);
        
        $testValue = '2';
        $realValue = UnauthorizedException::NON_INSCRIT;
        $this->assertNotEquals($testValue, $realValue);
        
        $testValue = '0';
        $realValue = UnauthorizedException::MAUVAIS_PROFIL;
        $this->assertNotEquals($testValue, $realValue);
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
